server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/integradora5d?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=20243ds029@utez.edu.mx
spring.mail.password=qcmz wfpq votb srdq
#spring.mail.username=${MAIL_USER}
#spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=Hhsdgbcj$$5/)))/&%$Tafads0ihbsjbbcbshghdggvvHbinHibiscusHhhgagdh!!!CasefdgdagTayrlodSwiftfthajydcnghv%&/#(/(GVYYDhguhgdpsdps