spring.application.name=integradora5d
spring.profiles.active=dev
jwt.expiration-ms=86400000
jwt.secret=Hhsdgbcj$$5/)))/&%$Tafads0ihbsjbbcbshghdggvvHbinHibiscusHhhgagdh!!!CasefdgdagTayrlodSwiftfthajydcnghv%&/#(/(GVYYDhguhgdpsdps

server.port=8085

spring.mail.host=smtp.gmail.com
spring.mail.port=587